### PR TITLE
Bump version to 0.7.4

### PR DESCRIPTION
**Pull request by nehaljwani**

### CODE REVIEW

**Comment by nehaljwani** [comment]
@conda-forge-admin, please add noarch: python

**Comment by jasongrout** [comment]
ping @ericmjl @dpryan79 - I think you two are the maintainers of this package. Can you review/merge this? I'd also like to submit a PR for building 0.5.4 based on top of this (#5).

**Comment by ericmjl** [comment]
Not a problem, everything looks good, so I will march.

**Comment by ericmjl** [comment]
Argh, autocorrect changed merge into march. Thanks for the ping!

**Pull request merged**
